import { ref } from "vue"

export const courses = ref([
  {
    id: 1,
    name: "Data Science & Analytics",
    type: "online",
    price: 1299,
    duration: "12 weeks",
    level: "Intermediate",
    description: "Master data analysis, machine learning, and statistical modeling with Python and R.",
    overview:
      "This comprehensive course covers everything from basic statistics to advanced machine learning algorithms. You'll work with real datasets and build practical projects that demonstrate your skills to potential employers.",
    modules: [
      { title: "Introduction to Data Science", description: "Overview of data science workflow and tools" },
      { title: "Python for Data Analysis", description: "Pandas, NumPy, and data manipulation" },
      { title: "Statistical Analysis", description: "Descriptive and inferential statistics" },
      { title: "Data Visualization", description: "Creating compelling charts and graphs" },
      { title: "Machine Learning Basics", description: "Supervised and unsupervised learning" },
      { title: "Advanced ML Techniques", description: "Deep learning and neural networks" },
      { title: "Big Data Tools", description: "Working with large datasets" },
      { title: "Capstone Project", description: "End-to-end data science project" },
    ],
  },
  {
    id: 2,
    name: "Business Administration MBA",
    type: "campus",
    price: 45000,
    duration: "2 years",
    level: "Advanced",
    description: "Comprehensive MBA program focusing on leadership, strategy, and business innovation.",
    overview:
      "Our MBA program is designed for working professionals who want to advance their careers. With evening and weekend classes, you can continue working while earning your degree.",
    modules: [
      { title: "Strategic Management", description: "Corporate strategy and competitive analysis" },
      { title: "Financial Management", description: "Corporate finance and investment decisions" },
      { title: "Marketing Strategy", description: "Brand management and market analysis" },
      { title: "Operations Management", description: "Supply chain and process optimization" },
      { title: "Leadership & Ethics", description: "Ethical decision making and team leadership" },
      { title: "International Business", description: "Global markets and cross-cultural management" },
      { title: "Entrepreneurship", description: "Starting and scaling new ventures" },
      { title: "Capstone Consulting", description: "Real-world business consulting project" },
    ],
  },
  {
    id: 3,
    name: "Web Development Bootcamp",
    type: "online",
    price: 899,
    duration: "16 weeks",
    level: "Beginner",
    description: "Full-stack web development with HTML, CSS, JavaScript, React, and Node.js.",
    overview:
      "Transform your career with our intensive web development bootcamp. Learn the most in-demand technologies and build a portfolio of real-world projects.",
    modules: [
      { title: "HTML & CSS Fundamentals", description: "Building responsive web layouts" },
      { title: "JavaScript Essentials", description: "Programming fundamentals and DOM manipulation" },
      { title: "React Development", description: "Modern frontend framework and components" },
      { title: "Node.js & Express", description: "Server-side JavaScript development" },
      { title: "Database Design", description: "SQL and NoSQL database management" },
      { title: "API Development", description: "RESTful services and authentication" },
      { title: "Deployment & DevOps", description: "Cloud hosting and CI/CD pipelines" },
      { title: "Portfolio Projects", description: "Build and deploy professional applications" },
    ],
  },
  {
    id: 4,
    name: "Digital Marketing Mastery",
    type: "online",
    price: 699,
    duration: "8 weeks",
    level: "Intermediate",
    description: "Complete digital marketing strategy including SEO, social media, and analytics.",
    overview:
      "Learn to create and execute digital marketing campaigns that drive real business results. This course covers all major digital marketing channels and tools.",
    modules: [
      { title: "Digital Marketing Strategy", description: "Planning and goal setting" },
      { title: "Search Engine Optimization", description: "Organic traffic and keyword research" },
      { title: "Pay-Per-Click Advertising", description: "Google Ads and Facebook advertising" },
      { title: "Social Media Marketing", description: "Content strategy and community building" },
      { title: "Email Marketing", description: "Automation and conversion optimization" },
      { title: "Analytics & Reporting", description: "Measuring and improving campaign performance" },
    ],
  },
  {
    id: 5,
    name: "Cybersecurity Fundamentals",
    type: "campus",
    price: 2499,
    duration: "20 weeks",
    level: "Intermediate",
    description: "Comprehensive cybersecurity training covering network security, ethical hacking, and compliance.",
    overview:
      "Prepare for a career in cybersecurity with hands-on training in our state-of-the-art security lab. Learn from industry experts and gain practical experience.",
    modules: [
      { title: "Network Security Basics", description: "Firewalls, VPNs, and network protocols" },
      { title: "Ethical Hacking", description: "Penetration testing and vulnerability assessment" },
      { title: "Incident Response", description: "Security breach detection and response" },
      { title: "Compliance & Governance", description: "Regulatory requirements and frameworks" },
      { title: "Cryptography", description: "Encryption and digital signatures" },
      { title: "Security Tools", description: "Industry-standard security software" },
      { title: "Risk Assessment", description: "Identifying and mitigating security risks" },
      { title: "Capstone Project", description: "Real-world security implementation" },
    ],
  },
  {
    id: 6,
    name: "UX/UI Design Certificate",
    type: "online",
    price: 1099,
    duration: "14 weeks",
    level: "Beginner",
    description: "User experience and interface design with industry-standard tools and methodologies.",
    overview:
      "Learn to create user-centered designs that solve real problems. This course combines design theory with practical skills using tools like Figma and Adobe Creative Suite.",
    modules: [
      { title: "Design Thinking Process", description: "User-centered design methodology" },
      { title: "User Research Methods", description: "Interviews, surveys, and usability testing" },
      { title: "Wireframing & Prototyping", description: "Low and high-fidelity design mockups" },
      { title: "Visual Design Principles", description: "Color theory, typography, and layout" },
      { title: "Interaction Design", description: "Micro-interactions and user flows" },
      { title: "Design Systems", description: "Creating consistent design languages" },
      { title: "Portfolio Development", description: "Showcasing your design work effectively" },
    ],
  },
])
